# Tuesday, January 29, 2012

## 10:56 AM - tracebacks

Use `traceback.format_exc()` or `traceback.print_exc()` to get a traceback for
the last exception.
